export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Denis Claudiano",
  },
  {
    id:2,
    profilePicture: "assets/person/5.jpg",
    username: "Danilo Carlotti",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Chewbacca",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Luke Skywalker",
  },
  {
    id:5,
    profilePicture: "assets/person/2.jpeg",
    username: "Darth Vader"
  },
  {
    id:6,
    profilePicture: "assets/person/9.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/6.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Trabalho duro.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
    workStatus: "Trabalho concluido",
  },
  {
    id: 2,
    desc: "Eu e meu chapéu lindo.",
    photo: "assets/post/13.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Finalizado :)",
    photo: "assets/post/12.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Sempre por eles.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Mude o mundo fazendo o bem.",
    photo: "assets/post/14.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Estudar é o futuro!!!",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];

export const Communities = [
  {
    id:1,
    profilePicture: "assets/community/1.jpeg",
    username: "Pedreira",
  },
  {
    id:2,
    profilePicture: "assets/community/3.jpeg",
    username: "Quilombola",
  },
  {
    id:3,
    profilePicture: "assets/community/5.jpeg",
    username: "Madalena",
  },
  {
    id:4,
    profilePicture: "assets/community/7.jpeg",
    username: "Barroca",
  },
  {
    id:5,
    profilePicture: "assets/community/8.jpeg",
    username: "Vila Prel",
  },
]

export const PostCommunities = [
  {
    id: 1,
    desc: "Melhorando a comunidade",
    photo: "assets/communityPosts/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
    workStatus: "Trabalho concluido",
  },
  {
    id: 2,
    desc: "Bora Galera!!!",
    photo: "assets/communityPosts/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "comunidade agil :)",
    photo: "assets/communityPosts/3.jpeg",
    date: "30 mins ago",
    userId: 3,
    like: 9,
    comment: 44,
  },
  {
    id: 4,
    desc: "Assim que se faz",
    photo: "assets/communityPosts/4.jpeg",
    date: "35 mins ago",
    userId: 4,
    like: 44,
    comment: 10,
  },
  {
    id: 5,
    desc: "Muito talento",
    photo: "assets/communityPosts/7.jpeg",
    date: "38 mins ago",
    userId: 5,
    like: 56,
    comment: 19,
  },
]

export const HomeUsers = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Denis Claudiano",
  },
  {
    id:2,
    profilePicture: "assets/community/1.jpeg",
    username: "Pedreira",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Chewbacca",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Luke Skywalker",
  },
  {
    id:5,
    profilePicture: "assets/person/2.jpeg",
    username: "Darth Vader"
  },
  {
    id:6,
    profilePicture: "assets/person/9.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/6.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const HomePosts = [
  {
    id: 1,
    desc: "Trabalho duro.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
    workStatus: "Trabalho concluido",
  },
  {
    id: 2,
    desc: "Melhorando a comunidade",
    photo: "assets/communityPosts/1.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 32,
    comment: 9,
    workDone: false,
  },
  {
    id: 3,
    desc: "Finalizado :)",
    photo: "assets/post/12.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Sempre por eles.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Mude o mundo fazendo o bem.",
    photo: "assets/post/14.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Estudar é o futuro!!!",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];